### ISSUE TITLE
Fix 'Edit on Github' to point to correct url

### ISSUE THREAD

**Issue by thomaszwagerman** [bas-amop/PolarRoute-server#62]
In the docs, the 'Edit on Github' button redirects to `master/docs/*.md`, but `master` should be `main`.

`master` is (for now?) annoyingly default in the [mkdocs configuration](https://www.mkdocs.org/user-guide/configuration/#edit_uri).

In mkdocs.yml, we will need to add:
```yml
# Already present
repo_url: https://github.com/bas-amop/PolarRoute-server
# New
edit_uri: edit/main/docs/
```
